// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UBUGenTreeMVC.Data;

#nullable disable

namespace UBUGenTreeMVC.Migrations
{
    [DbContext(typeof(MvcUserContext))]
    [Migration("20231016220616_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("UBUGenTreeMVC.Models.Usuario", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("_ancestrosJSON")
                        .HasColumnType("TEXT");

                    b.Property<string>("_contrasenaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("_estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("_intentosFallidos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("_rol")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("_ultimoIngreso")
                        .HasColumnType("TEXT");

                    b.HasKey("_id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
